"""Constants used by the Eero integration."""

from .api.const import (
    ACTIVITY_ADBLOCK_DAY,
    ACTIVITY_ADBLOCK_MONTH,
    ACTIVITY_ADBLOCK_WEEK,
    ACTIVITY_BLOCKED_DAY,
    ACTIVITY_BLOCKED_MONTH,
    ACTIVITY_BLOCKED_WEEK,
    ACTIVITY_DATA_USAGE_DAY,
    ACTIVITY_DATA_USAGE_MONTH,
    ACTIVITY_DATA_USAGE_WEEK,
    ACTIVITY_INSPECTED_DAY,
    ACTIVITY_INSPECTED_MONTH,
    ACTIVITY_INSPECTED_WEEK,
)

ACTIVITIES_DEFAULT = [
    ACTIVITY_DATA_USAGE_WEEK,
]
ACTIVITIES_PREMIUM = [
    ACTIVITY_ADBLOCK_DAY,
    ACTIVITY_ADBLOCK_WEEK,
    ACTIVITY_ADBLOCK_MONTH,
    ACTIVITY_DATA_USAGE_DAY,
    ACTIVITY_DATA_USAGE_WEEK,
    ACTIVITY_DATA_USAGE_MONTH,
    ACTIVITY_INSPECTED_DAY,
    ACTIVITY_INSPECTED_WEEK,
    ACTIVITY_INSPECTED_MONTH,
    ACTIVITY_BLOCKED_DAY,
    ACTIVITY_BLOCKED_WEEK,
    ACTIVITY_BLOCKED_MONTH,
]

ACTIVITIES_DATA_USAGE_DEFAULT = [
    ACTIVITY_DATA_USAGE_WEEK,
]
ACTIVITIES_DATA_USAGE_PREMIUM = [
    ACTIVITY_DATA_USAGE_DAY,
    ACTIVITY_DATA_USAGE_WEEK,
    ACTIVITY_DATA_USAGE_MONTH,
]

ATTR_BLOCKED_APPS = "blocked_apps"
ATTR_TARGET_NETWORK = "target_network"
ATTR_TARGET_PROFILE = "target_profile"

CONF_ACTIVITY = "activity"
CONF_ACTIVITY_CLIENTS = "clients"
CONF_ACTIVITY_EEROS = "eeros"
CONF_ACTIVITY_NETWORK = "network"
CONF_ACTIVITY_PROFILES = "profiles"
CONF_BACKUP_NETWORKS = "backup_networks"
CONF_CLIENTS = "clients"
CONF_CODE = "code"
CONF_CONSIDER_HOME = "consider_home"
CONF_EEROS = "eeros"
CONF_FILTER_EXCLUDE = "exclude"
CONF_FILTER_INCLUDE = "include"
CONF_LOGIN = "login"
CONF_NAME = "name"
CONF_NETWORKS = "networks"
CONF_PROFILES = "profiles"
CONF_USER_TOKEN = "user_token"
CONF_WIRED_CLIENTS = "wired_clients"
CONF_WIRED_CLIENTS_FILTER = "wired_clients_filter"
CONF_WIRELESS_CLIENTS = "wireless_clients"
CONF_WIRELESS_CLIENTS_FILTER = "wireless_clients_filter"

DATA_API = "api"
DATA_COORDINATOR = "coordinator"
DATA_UPDATE_LISTENER = "update_listener"

DOMAIN = "eero"

MANUFACTURER = "eero"

MODEL_BACKUP_NETWORK = "Backup Network"
MODEL_CLIENT_WIRED = "Client (Wired)"
MODEL_CLIENT_WIRELESS = "Client (Wireless)"
MODEL_EERO = "eero"
MODEL_NETWORK = "Network"
MODEL_PROFILE = "Profile"

RELEASE_URL = (
    "https://support.eero.com/hc/en-us/articles/209636523-eero-Software-Release-Notes"
)

SERVICE_SET_BLOCKED_APPS = "set_blocked_apps"

CONF_MISCELLANEOUS = "miscellaneous"
CONF_PREFIX_NETWORK_NAME = "prefix_network_name"
CONF_RESOURCES = "resources"
CONF_SAVE_RESPONSES = "save_responses"
CONF_SHOW_EERO_LOGO = "show_eero_logo"
CONF_SUFFIX_CONNECTION_TYPE = "suffix_connection_type"
CONF_TIMEOUT = "timeout"

VALUES_CLIENTS_FILTER = [CONF_FILTER_EXCLUDE, CONF_FILTER_INCLUDE]

MIN_CONSIDER_HOME: int = 0
MAX_CONSIDER_HOME: int = 30
STEP_CONSIDER_HOME: int = 1

MIN_SCAN_INTERVAL: int = 30
MAX_SCAN_INTERVAL: int = 600
STEP_SCAN_INTERVAL: int = 30

MIN_TIMEOUT: int = 10
MAX_TIMEOUT: int = 60
STEP_TIMEOUT: int = 5

DEFAULT_CONSIDER_HOME: int = 0
DEFAULT_PREFIX_NETWORK_NAME: bool = True
DEFAULT_SAVE_LOCATION: str = f"/config/custom_components/{DOMAIN}/api/responses"
DEFAULT_SAVE_RESPONSES: bool = False
DEFAULT_SCAN_INTERVAL: int = 120
DEFAULT_SHOW_EERO_LOGO: bool = False
DEFAULT_SUFFIX_CONNECTION_TYPE: bool = True
DEFAULT_TIMEOUT: int = 30
DEFAULT_WIRED_CLIENTS_FILTER: str = CONF_FILTER_INCLUDE
DEFAULT_WIRELESS_CLIENTS_FILTER: str = CONF_FILTER_INCLUDE
